name: Bearer

# Run on every Pull Request event
on:
  pull_request:

# Define GitHub Pages url 
env: 
  gh_pages_url: https://tetrisiq.github.io/env_test/

jobs:
# Generate a Json report to check if there are findings
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: json
          output: securityTest.json
          exit-code: 0
      - id: echo 
        run: echo security_finding=$(cat securityTest.json | jq '. != {}')  >> $GITHUB_OUTPUT
    outputs:
      security_finding: ${{ steps.echo.outputs.security_finding }}

# Generate HTML report if there are findings, otherwiese skip this job 
  generate_html:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.security_finding == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: html
          output: securityTest.html
          exit-code: 0
      - uses: actions/upload-artifact@v3
        with:
          name: securityHTML
          path: securityTest.html

# Create a comment in the PR with a link to the HTML report 
  comment_to_PR:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.security_finding == 'true' }}
    permissions:
        contents: 'read'
        id-token: 'write'
        pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('https://avatars.githubusercontent.com/u/36886676?s=48&v=4')
            })

            const commentBody = "# \![](https://avatars.githubusercontent.com/u/36886676?s=48&v=4) Bearer Report\nWe found some issues in your `code`:\nTake a look at the report here: ${{ env.gh_pages_url }}pr/${{ github.event.number }}/security/securityTest.html";

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              })
            }

# Upload the HTML page to GH pages branch            
  upload_html_to_page:
    runs-on: ubuntu-latest
    needs: generate_html
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: securityHTML
          path: pr/${{ github.event.number }}/security
      - name: Commit report
        run: |
          git config --global user.name 'TetrisIQ'
          git config --global user.email '24246993+TetrisIQ@users.noreply.github.com'
          git add . 
          git commit -am "Automated report"
          git push
    