name: Bearer

on:
  pull_request:
  

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: json
          output: securityTest.json
          exit-code: 0
      - run: cat securityTest.json
      - run: echo security_finding=$(cat securityTest.json | jq '. != {}')
      - id: echo 
        run: echo security_finding=$(cat securityTest.json | jq '. != {}')  >> $GITHUB_OUTPUT

    outputs:
      security_finding: ${{ steps.echo.outputs.security_finding }}
  generateHTML:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.security_finding == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: html
          output: securityTest.html
          exit-code: 0
      - uses: actions/upload-artifact@v3
        with:
          name: securityHTML
          path: securityTest.html
  comment_to_PR:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.security_finding == 'true' }}
    permissions:
        contents: 'read'
        id-token: 'write'
        pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Thanks for reporting')
            })

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: '👋 Thanks for reporting! UPDATE'
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting!'
              })
            }
  upload_html_to_page:
    runs-on: ubuntu-latest
    needs: generateHTML
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: securityHTML
          path: pr/${{ github.event.number }}/security
