name: Bearer

# Run on every Pull Request event
on:
  pull_request:

jobs:
# Generate a Json report to check if there are findings
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write
    steps:
      - uses: TetrisIQ/bearer-pr-test@master
     